version: '3.8'

services:
  # GraphRAG Agent 服务
  graphrag-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - OPENAI_EMBEDDINGS_MODEL=text-embedding-3-large
      - OPENAI_LLM_MODEL=gpt-4o-mini
      - TEMPERATURE=0
      - MAX_TOKENS=2000
      - VERBOSE=true
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=12345678
      - CACHE_EMBEDDING_PROVIDER=openai
      - LANGSMITH_TRACING=false
    depends_on:
      - neo4j
    volumes:
      - ./files:/app/files
      - ./cache:/app/cache
    restart: unless-stopped

  # Neo4j 数据库
  neo4j:
    image: neo4j:5.15
    environment:
      - NEO4J_AUTH=neo4j/12345678
      - NEO4J_PLUGINS=["gds"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*,apoc.*
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: